#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        # Set the default settings of the service package to those expected by
        # OpenMediaVault.
        if [ -z "$2" ]; then
            echo "Updating init script links and actions."
            #deb-systemd-helper disable syncwatch.service >/dev/null || true
            #deb-systemd-invoke stop syncwatch.service >/dev/null || true

        fi

        # Activate package triggers.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale

        # Initialize and migrate configuration database.
        echo "Updating configuration database ..."
        omv-confdbadm create "conf.service.syncwatch"
        if [ -n "$2" ]; then
            omv-confdbadm migrate "conf.service.syncwatch" "${2}"
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
